version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vote-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vote_system
      MYSQL_USER: vote_user
      MYSQL_PASSWORD: vote_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vote-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "root:password@tcp(mysql:3306)/vote_system?charset=utf8mb4&parseTime=True&loc=Local"
      PORT: "8080"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vote-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  mysql_data: 